package constants

// Xendit Callback Queue Action
const XenditCallbackAccountCreated = "account-created-xendit"
const XenditCallbackFixedVirtualAccountPaid = "fixed-virtual-account-paid-xendit"
const XenditCallbackFixedVirtualAccountCreated = "fixed-virtual-account-created-xendit"
const XenditCallbackOTCPaid = "retail-outlet-paid-xendit"
const XenditCallbackCardAuthentication = "cards-authentication-xendit"
const XenditCallbackCardTokenization = "card-tokenization-xendit"
const XenditDirectDebitAccountLinked = "direct-debit-account-linked-xendit"
const XenditDirectDebitPaymentCompleted = "direct-debit-payment-completed-xendit"
const XenditDirectDebitExpired = "direct-debit-expired-xendit"
const XenditDirectDebitRefundFinalized = "direct-debit-refund-finalized-xendit"
const XenditBalanceTransactionReport = "report-xendit"
const XenditPaymentRequestPaymentSucceeded = "payment-request-payment-succeeded-xendit"
const XenditPaymentRequestAwaitingCapture = "payment-request-awaiting-capture-xendit"
const XenditPaymentRequestPaymentPending = "payment-request-payment-pending-xendit"
const XenditPaymentRequestPaymentFailed = "payment-request-payment-failed-xendit"
const XenditPaymentRequestCaptureSuccess = "payment-request-capture-success-xendit"
const XenditPaymentRequestCaptureFailed = "payment-request-capture-failed-xendit"
const XenditRefundSuccess = "refund-success-xendit"
const XenditRefundFailed = "refund-failed-xendit"
const XenditRecurring = "recurring-xendit"
const XenditPayLater = "paylater-xendit"
const XenditQRCodes = "qrcodes-xendit"
const XenditDisbursementSent = "disbursement-sent-xendit"
const XenditBatchDisbursementSent = "batch-disbursement-sent-xendit"
const XenditPayoutSent = "payouts-xendit"
const XenditInvoice = "invoice-paid-xendit"
const XenditXenPlatformAccountCreated = "xen-platform-account-created-xendit"
const XenditXenPlatformAccountUpdated = "xen-platform-account-updated-xendit"
const XenditXenPlatformAccountHolderKycStatus = "xen-platform-account-holder-kyc-xendit"
const XenditXenPlatformAccountHolderCapabilitiesStatus = "xen-platform-account-holder-capabilities-xendit"
const XenditXenPlatformAccountSuspension = "xen-platform-account-suspension-xendit"
const XenditPaymentMethod = "payment-method-xendit"
const XenditEWalletsPaymentStatus = "e-wallet-payment-xendit"
const XenditEWalletsReconciliationUpdate = "e-wallet-reconciliation-xendit"
